=== rsreevishal/MySQL-GUI/target/classes/ftl_templates/expression_template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
	targetNamespace="http://www.mysqlgui.org/expression_template"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://www.mysqlgui.org/expression_template">
	<element name="expressions">
		<complexType>
			<sequence>
				<element name="expression" maxOccurs="unbounded" minOccurs="1">
					<complexType>
						<sequence>
							<element name="template" minOccurs="1" maxOccurs="1">
								<simpleType>
								 <restriction base="string">
								 </restriction>
								</simpleType>
							</element>
						</sequence>
						<attribute name="id" type="ID"></attribute>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>

</schema>

=== rsreevishal/MySQL-GUI/target/classes/ftl_templates/expression_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:expressions
	xmlns:tns="http://www.mysqlgui.org/expression_template"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mysqlgui.org/expression_template expression_template.xsd ">
	<tns:expression id="IdToken">
		<tns:template>IdToken.ftl</tns:template>
	</tns:expression>
	<tns:expression id="FormExpr">
		<tns:template>FormExpr.ftl</tns:template>
	</tns:expression>
	<tns:expression id="ListToken">
		<tns:template>ListToken.ftl</tns:template>
	</tns:expression>
	<tns:expression id="FormInputExpr">
		<tns:template>FormInputExpr.ftl</tns:template>
	</tns:expression>
	<tns:expression id="TextToken">
		<tns:template>TextToken.ftl</tns:template>
	</tns:expression>
	<tns:expression id="OperatorExpr">
		<tns:template>OperatorExpr.ftl</tns:template>
	</tns:expression>
	<tns:expression id="ConditionExpr">
		<tns:template>ConditionExpr.ftl</tns:template>
	</tns:expression>
	<tns:expression id="FormReportExpr">
		<tns:template>FormReportExpr.ftl</tns:template>
	</tns:expression>
</tns:expressions>
